name: Deploy Frontend

on:
  push:
    branches: [ "main" ] # 监听 main 分支的推送

# 设置 GitHub 权限，允许 Actions 修改 Pages 内容
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9 # 或者指定你本地用的版本，如 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm" # 现在的 setup-node 已经原生支持缓存 pnpm 了

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist